# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-03 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
    ]
