# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scrapyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
